FROM node:12.13.0-alpine

# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# copy the app, note .dockerignore
COPY . /usr/src/nuxt-app/
COPY ./deployment/dev/.env /usr/src/nuxt-app/

RUN npm install && \
  npm run build

EXPOSE 4000

# Not fully sure what this does, 
# but without it the image is borked
ENV NUXT_HOST=0.0.0.0

# start the app
CMD [ "npm", "run", "start" ]
